'use strict';
const $ = (q, root=document) => root.querySelector(q);
const $$ = (q, root=document) => [...root.querySelectorAll(q)];
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ICONS = {
  grid:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',
  compare:'<path d="M4 7h16m-4-4 4 4-4 4M20 17H4m4-4-4 4 4 4"/>',
  file:'<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><path d="M14 2v6h6M8 13h8M8 17h5"/>',
  folder:'<path d="M3 7V5a2 2 0 0 1 2-2h5l2 3h7a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V7Z"/>',
  shield:'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6z"/><path d="m8 12 3 3 5-6"/>',
  plus:'<path d="M12 5v14M5 12h14"/>', arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>', chevron:'<path d="m9 5 7 7-7 7"/>', down:'<path d="m6 9 6 6 6-6"/>', back:'<path d="M19 12H5m5-5-5 5 5 5"/>',
  check:'<path d="m5 12 4 4L19 6"/>', close:'<path d="m6 6 12 12M6 18 18 6"/>', search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',
  clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>', info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7v.1"/>',
  help:'<circle cx="12" cy="12" r="9"/><path d="M9.5 8a2.6 2.6 0 0 1 5 1c0 2-2.5 2-2.5 4M12 17v.1"/>',
  settings:'<path d="m10 3-1 3-3 1-2 3 2 2-1 3 3 3 3-1 2 2 3-1 1-3 3-1v-4l-3-1-1-3-3-1z"/><circle cx="12" cy="11" r="3"/>',
  users:'<circle cx="9" cy="8" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3M17 5a3 3 0 0 1 0 6M18 15a5 5 0 0 1 3 5"/>',
  logout:'<path d="M9 4H4v16h5M13 8l4 4-4 4m-4-4h12"/>', building:'<rect x="5" y="3" width="14" height="18" rx="2"/><path d="M9 7h1m4 0h1m-6 4h1m4 0h1m-5 10v-5h4v5"/>',
  upload:'<path d="M12 16V3m-5 5 5-5 5 5M4 16v4a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-4"/>', download:'<path d="M12 3v13m-5-5 5 5 5-5M4 16v4a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-4"/>',
  spark:'<path d="m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5zM20 2v4M18 4h4"/>',
  link:'<path d="m10 13 4-4m-6 6-1 1a4 4 0 0 1-6-6l4-4a4 4 0 0 1 6 0m2 2 1-1a4 4 0 0 1 6 6l-4 4a4 4 0 0 1-6 0"/>',
  alert:'<path d="m12 3 10 18H2zM12 9v5M12 17v.1"/>', branch:'<rect x="9" y="2" width="6" height="5" rx="1"/><rect x="2" y="17" width="6" height="5" rx="1"/><rect x="16" y="17" width="6" height="5" rx="1"/><path d="M12 7v5H5v5m7-5h7v5"/>',
  table:'<rect x="3" y="3" width="18" height="18" rx="2"/><path d="M3 9h18M3 15h18M9 3v18"/>', eye:'<path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>',
  menu:'<path d="M4 6h16M4 12h16M4 18h16"/>', lock:'<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3M12 14v3"/>',
};
function icon(name, size=18) { return `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${ICONS[name] || ICONS.file}</svg>`; }
const S = {user:null, config:null, cases:[], current:null, setup:false, canSetup:false, files:{before:[],after:[]}, title:'', useAI:true, tab:'findings', filter:'important', review:'all', query:'', page:1, timer:null, routeToken:0, modal:null, activeFinding:null, focusBefore:null};
const writable = () => S.user && S.user.role !== 'viewer';
const fmtDate = n => new Date(n*1000).toLocaleDateString(lang==='kz'?'kk-KZ':'ru-RU',{day:'numeric',month:'short',year:'numeric'});
const fmtTime = n => new Date(n*1000).toLocaleString(lang==='kz'?'kk-KZ':'ru-RU');
const bytes = n => n>1024*1024 ? `${(n/1024/1024).toFixed(1)} МБ` : `${Math.max(1,Math.round(n/1024))} КБ`;
const badge = (label,color='purple') => `<span class="pill ${color}">${esc(label)}</span>`;
const statusBadge = c => badge(t(c.status==='complete'?'complete':c.status==='failed'?'failed':'processing'), c.status==='complete'?'green':c.status==='failed'?'red':'purple');
const reviewBadge = f => f.review !== 'pending' ? badge(t(f.review),f.review==='confirmed'?'green':'gray') : '';
const kindColor = k => ['missing','unit_removed','conflict'].includes(k)?'red':k==='modality'?'amber':['added','unit_added','unchanged'].includes(k)?'green':['editorial','renumbered'].includes(k)?'gray':'purple';
const langSwitch = () => `<div class="lang-switch" aria-label="Language"><button type="button" data-action="language" data-lang="ru" class="${lang==='ru'?'active':''}" aria-pressed="${lang==='ru'}">RU</button><button type="button" data-action="language" data-lang="kz" class="${lang==='kz'?'active':''}" aria-pressed="${lang==='kz'}">ҚАЗ</button></div>`;
function toast(message,error=false) { const el=$('#toast'); el.textContent=message; el.className=`toast visible${error?' error':''}`; clearTimeout(toast.timer); toast.timer=setTimeout(()=>el.classList.remove('visible'),4500); }
async function api(path, options={}) {
  let response;
  try { response=await fetch(path,{credentials:'same-origin',...options,headers:options.body instanceof FormData ? options.headers : {'Content-Type':'application/json',...options.headers}}); }
  catch { throw new Error(t('networkError')); }
  const data=await response.json().catch(()=>({}));
  if (!response.ok) {
    if(response.status===401 && S.user) {S.user=null;closeModal();renderAuth();}
    let message=typeof data.detail==='string'?data.detail:t('error');
    if(Array.isArray(data.detail)) message=data.detail.map(e=>e.msg).join(' · ');
    throw new Error(message);
  }
  return data;
}
function go(path) { const hash='#/'+path; if(location.hash===hash) route(); else location.hash=hash; }
function loading() { return `<div class="loading"><div class="spinner"></div>${t('loading')}</div>`; }
function empty(title, text='', action='') { return `<div class="empty"><div class="empty-icon">${icon('folder',27)}</div><h3>${esc(title)}</h3>${text?`<p>${esc(text)}</p>`:''}${action}</div>`; }
function btn(label,action,ic='plus',type='primary',extra='') { return `<button type="button" class="btn ${type}" data-action="${action}" ${extra}>${icon(ic,16)}<span>${esc(label)}</span></button>`; }
function shell(view) {
  const nav=[['home','grid'],['cases','compare'],['docs','folder'],['method','help']];
  const adminNav=S.user.role==='admin'?`<a href="#/team" class="${view==='team'?'active':''}">${icon('users')}${t('team')}</a><a href="#/audit" class="${view==='audit'?'active':''}">${icon('clock')}${t('audit')}</a>`:'';
  $('#app').innerHTML=`<aside class="sidebar" id="sidebar"><a class="brand" href="#/home"><img src="/assets/favicon.svg" alt="">AI-NAM <small>WORKSPACE</small></a><div class="workspace-card"><div class="workspace-avatar">${icon('building',18)}</div><div><strong>AI-NAM</strong><small>${t('workspace')}</small></div></div><div class="nav-label">${t('platform')}</div><nav class="nav" aria-label="${t('workspace')}">${nav.map(([key,ic])=>`<a href="#/${key}" class="${view===key || (view==='case'&&key==='cases') || (view==='new'&&key==='cases')?'active':''}">${icon(ic)}${t(key)}${key==='cases'&&S.cases.length?`<span class="nav-count">${S.cases.length}</span>`:''}</a>`).join('')}</nav><div class="sidebar-bottom"><nav class="nav">${adminNav}<a href="#/settings" class="${view==='settings'?'active':''}">${icon('settings')}${t('settings')}</a></nav><div class="private-card"><div class="flex">${icon('shield',14)}${t('internal')}</div><p>${t('auditNote')}</p></div><div class="user-card"><div class="avatar">${esc(S.user.name.slice(0,2).toUpperCase())}</div><div class="user-text"><strong>${esc(S.user.name)}</strong><small>${t(S.user.role)}</small></div><button class="icon-button" data-action="logout" aria-label="${t('logout')}" title="${t('logout')}">${icon('logout',17)}</button></div></div></aside><div class="shell"><header class="topbar"><button class="icon-button mobile-menu" data-action="menu" aria-label="Menu">${icon('menu')}</button><div class="breadcrumb">${t('workspace')}${icon('chevron',11)}<strong>${t(view==='case'?'cases':view==='new'?'newAnalysis':view)}</strong></div><div class="top-actions"><span class="pill green internal-pill"><span class="dot"></span>${t('internal')}</span>${langSwitch()}${writable()?btn(t('newAnalysis'),'new','plus','primary'):''}</div></header><main class="main" id="main" tabindex="-1"></main></div>`;
}
function footer() {return `<footer class="page-footer"><span>AI-NAM · ${t('platform')}</span><span>${icon('shield',12)}${t('sourcesVerified')}</span></footer>`;}
function renderAuth() {
  clearTimeout(S.timer);
  const setup=S.setup;
  document.documentElement.lang=lang==='kz'?'kk':'ru';
  $('#app').innerHTML=`<div class="auth-layout"><section class="auth-visual"><div class="brand"><img src="/assets/favicon.svg" alt="">AI-NAM</div><div class="auth-copy"><div class="eyebrow">${t('internal').toUpperCase()}</div><h1>${esc(t('authHero'))}</h1><p>${t('authText')}</p></div><small>AI-NAM · ${t('platform')}</small></section><main class="auth-form-panel" id="main"><div class="auth-lang">${langSwitch()}</div><form class="auth-form" id="auth-form"><div class="eyebrow" style="margin-bottom:17px">AI-NAM WORKSPACE</div><h2>${t(setup?'setupTitle':'loginTitle')}</h2><p>${t(setup?'setupText':'loginText')}</p><div id="auth-error" role="alert"></div>${setup?`<label class="field"><span>${t('name')}</span><input name="name" autocomplete="name" minlength="2" maxlength="100" required></label>`:''}<label class="field"><span>${t('username')}</span><input name="username" autocomplete="username" pattern="[a-zA-Z0-9_.\-]+" minlength="3" maxlength="60" required placeholder="name.surname"></label><label class="field"><span>${t('password')}</span><input type="password" name="password" autocomplete="${setup?'new-password':'current-password'}" minlength="${setup?10:1}" maxlength="200" required>${setup?`<small>${t('passwordHint')}</small>`:''}</label>${setup?`<label class="field"><span>${t('confirmPassword')}</span><input type="password" name="confirmation" autocomplete="new-password" required></label>`:''}${setup&&!S.canSetup?`<div class="notice warn">${t('setupLocal')}</div>`:`<button class="btn primary full lg" type="submit">${t(setup?'setup':'login')}${icon('arrow',17)}</button>`}<div class="auth-form-footer">${icon('lock',12)}${t('internal')}</div></form></main></div>`;
}
async function boot() {
  $('#app').innerHTML=loading();
  try {const auth=await api('/api/auth/state');S.user=auth.user;S.setup=auth.setup_required;S.canSetup=auth.can_setup;if(!S.user)return renderAuth();await loadWorkspace();route();}
  catch(e){$('#app').innerHTML=`<div class="error-box card"><h2>${t('error')}</h2><p>${esc(e.message)}</p>${btn(t('retry'),'reload','compare')}</div>`;}
}
async function loadWorkspace() { [S.config,S.cases]=await Promise.all([api('/api/config'),api('/api/cases')]); S.useAI=S.config.ai.available&&S.config.ai.local; }
function renderHome() {
  const docs=S.cases.reduce((n,c)=>n+(c.stats?.source_count||0),0), processing=S.cases.filter(c=>c.status==='processing').length;
  $('#main').innerHTML=`<div class="home-hero card"><div class="hero-copy"><div class="eyebrow">${t('heroEyebrow')}</div><h1>${esc(t('heroTitle'))}</h1><p>${t('heroText')}</p><div class="flex">${writable()?btn(t('start'),'new','plus','primary lg'):btn(t('cases'),'cases','compare','primary lg')}<a href="#/method" class="btn ghost">${t('method')}${icon('arrow',15)}</a></div></div><div class="hero-visual" aria-hidden="true"><div class="diagram-orbit"></div><svg class="diagram-wire" viewBox="0 0 400 305"><path d="M120 80 190 154 307 126M190 154 125 245"/></svg><div class="diagram-core">${icon('branch',32)}</div><div class="diagram-card one"><div class="flex"><div class="mini-icon">${icon('file',15)}</div><strong>${t('before')}</strong></div><div class="line"></div><div class="line"></div></div><div class="diagram-card two"><strong>${t('preserved')}</strong><div class="flex"><span class="pill green">${icon('check',10)}${t('sourcesVerified')}</span></div></div><div class="diagram-card three"><strong>${t('after')}</strong><div class="line"></div><div class="line"></div><span class="pill purple">+ ${t('newUnit')}</span></div></div></div><div class="stats-row">${[[S.cases.length,'comparisons','compare'],[docs,'documents','file'],[processing,'processing','clock']].map(([n,l,i])=>`<div class="stat-card card"><div class="stat-icon">${icon(i,20)}</div><div><div class="number">${n.toString().padStart(2,'0')}</div><p>${t(l)}</p></div></div>`).join('')}</div><div class="home-lower"><section class="card"><div class="card-heading"><h2>${t('recent')}</h2><a href="#/cases" class="link-button">${t('allCases')}${icon('arrow',13)}</a></div>${S.cases.length?S.cases.slice(0,4).map(caseRow).join(''):empty(t('noCases'),t('noCasesText'),writable()?`<button class="link-button" data-action="new">${t('start')}${icon('arrow',13)}</button>`:'')}</section><aside class="demo-card card"><div class="eyebrow">${t('demoTag')}</div><div class="demo-art" aria-hidden="true"><div class="file-art"><span>v8</span></div>${icon('arrow',19)}<div class="file-art"><span>v9</span></div></div><h3>${t('demoTitle')}</h3><p>${t('demoText')}</p><div class="demo-meta">${t('demoFiles')} · ${t('demoVersions')}</div>${writable()?btn(t('viewDemo'),'demo','spark','soft full'):''}</aside></div><div class="benefits">${[['link','sourceProof','sourceProofText'],['shield','privacy','privacyText']].map(([ic,title,text])=>`<div class="benefit">${icon(ic,20)}<div><h3>${t(title)}</h3><p>${t(text)}</p></div></div>`).join('')}</div>${footer()}`;
}
function caseRow(c) {return `<button class="case-row" data-action="case" data-id="${esc(c.id)}"><div class="case-icon">${icon('file',20)}</div><div class="case-info"><strong>${esc(c.title)}</strong><small>${fmtDate(c.created)} · ${esc(c.owner_name||'AI-NAM')}</small></div>${statusBadge(c)}<span class="case-arrow">${icon('chevron',16)}</span></button>`;}
function renderCases() {
  $('#main').innerHTML=`<div class="page-heading"><div><h1>${t('cases')}</h1><p>${t('casesSubtitle')}</p></div>${writable()?btn(t('newAnalysis'),'new'):''}</div><div class="card">${S.cases.length?`<div class="table-wrap"><table class="data-table"><thead><tr><th>${t('caseName')}</th><th>${t('created')}</th><th>${t('author')}</th><th>${t('status')}</th><th>${t('attention')}</th><th></th></tr></thead><tbody>${S.cases.map(c=>`<tr data-action="case" data-id="${c.id}" tabindex="0"><td><div class="flex">${icon('file',18)}<strong>${esc(c.title)}</strong></div></td><td>${fmtDate(c.created)}</td><td>${esc(c.owner_name)}</td><td>${statusBadge(c)}</td><td>${c.stats?.attention??'—'}</td><td>${icon('chevron',15)}</td></tr>`).join('')}</tbody></table></div>`:empty(t('noCases'),t('noCasesText'),writable()?btn(t('start'),'new'):'')}</div>${footer()}`;
}
function renderNew() {
  if(!writable())return go('cases');
  const ai=S.config.ai;
  $('#main').innerHTML=`<div class="stepper"><div class="step active"><span class="step-circle">1</span>${t('stepDocuments')}</div><span class="step-line"></span><div class="step"><span class="step-circle">2</span>${t('stepAnalysis')}</div><span class="step-line"></span><div class="step"><span class="step-circle">3</span>${t('stepResult')}</div></div><div class="page-heading"><div><h1>${t('uploadTitle')}</h1><p>${t('uploadSubtitle')}</p></div></div><form id="upload-form" class="card upload-card"><label class="field upload-title-field"><span>${t('caseTitle')}</span><input id="case-title" name="title" minlength="2" maxlength="160" required placeholder="${t('casePlaceholder')}" value="${esc(S.title)}"></label><div id="upload-error" role="alert"></div><div class="upload-grid">${['before','after'].map((side,i)=>`<section class="upload-panel"><div class="upload-panel-head"><div class="version-label">0${i+1}</div><div><h3>${t(side)}</h3><p>${t(side+'Hint')}</p></div></div><div class="drop-zone" data-drop="${side}"><div class="upload-icon">${icon('upload',22)}</div><strong>${t('dropTitle')}</strong><p>${t('dropOr')}</p><button type="button" class="btn sm" data-action="browse" data-side="${side}">${t('browse')}</button><input type="file" id="files-${side}" data-files="${side}" class="sr-only" accept=".docx,.pdf,.xlsx,.txt" multiple aria-label="${t(side)}"><small>${t('uploadFormats')}</small></div><div class="file-list" id="list-${side}"></div></section>`).join('')}</div><div class="upload-limit">${icon('info',12)}${t('uploadLimits')}</div><label class="ai-choice"><input type="checkbox" id="use-ai" ${S.useAI&&ai.available?'checked':''} ${!ai.available?'disabled':''}><div><div class="flex"><strong>${t('aiMode')}</strong>${ai.available?badge(ai.model, 'purple'):badge(t('disconnected'),'gray')}</div><p>${t(!ai.available?'aiUnavailable':ai.local?'aiLocal':'aiRemote')}</p></div></label><div class="upload-footer"><small>${icon('shield',14)}${t('auditNote')}</small><button class="btn primary lg" type="submit">${icon('compare',17)}${t('analyze')}${icon('arrow',16)}</button></div></form>${footer()}`;
  renderFiles();
}
function renderFiles() {
  for(const side of ['before','after']){
    const list=$('#list-'+side);if(!list)continue;
    list.innerHTML=S.files[side].map((file,i)=>`<div class="file-row"><span class="file-type">${esc(file.name.split('.').pop().toUpperCase())}</span><div class="file-name"><strong title="${esc(file.name)}">${esc(file.name)}</strong><small>${bytes(file.size)}</small></div><button class="icon-button" type="button" data-action="remove-file" data-side="${side}" data-index="${i}" aria-label="${t('removeFile')}: ${esc(file.name)}">${icon('close',14)}</button></div>`).join('');
  }
}
function addFiles(side, files) {
  let duplicate=false;
  for(const file of files){
    if(!/\.(docx|pdf|xlsx|txt)$/i.test(file.name)){toast(file.name+': '+t('unsupported'),true);continue;}
    if(file.size>20*1024*1024){toast(file.name+': '+t('tooLarge'),true);continue;}
    if(S.files[side].some(f=>f.name===file.name&&f.size===file.size)){duplicate=true;continue;}
    if(S.files[side].length>=20){toast(t('uploadLimits'),true);break;}
    const total=[...S.files.before,...S.files.after].reduce((n,f)=>n+f.size,0);
    if(total+file.size>100*1024*1024){toast(t('totalLarge'),true);break;}
    S.files[side].push(file);
  }
  if(duplicate)toast(t('duplicates'));
  renderFiles();
}
function renderProcessing(c) {
  if(c.result){if($('#main').dataset.stage===c.stage)return;if(!S.modal&&!$('#finding-search:focus')&&!$('#matrix-search:focus')){renderResult();$('#main').dataset.stage=c.stage;}return;}
  $('#main').innerHTML=`<div class="processing-card card"><div class="progress-orb">${icon('branch',34)}</div><h2>${t('analyzeTitle')}</h2><p>${t('analyzeText')}</p><div class="between"><strong class="small text-wrap">${esc(c.title)}</strong><span class="pill purple">${c.progress}%</span></div><div class="progress-track"><div style="width:${c.progress}%"></div></div><div class="progress-caption"><span>${esc(c.stage)}</span></div><div class="progress-steps">${[['stageRead',35],['stageMatch',66],['stageCheck',100]].map(([label,max],i)=>`<div class="progress-step ${c.progress>=max?'done':c.progress>=[0,35,66][i]?'active':''}">${icon(c.progress>=max?'check':c.progress>=[0,35,66][i]?'clock':'file',16)}${t(label)}</div>`).join('')}</div></div>`;
}
function accessButton(c){return `<button class="btn ghost" data-action="sharing">${icon(c.shared?'users':'lock',14)}${t(c.shared?'sharedCase':'privateCase')}</button>`;}
function sharingModal(){const c=S.current,manage=S.user.role==='admin'||c.owner_id===S.user.id;openModal(`${dialogHeader(t('accessTitle'))}<div class="modal-body"><p>${t(c.shared?'sharedCase':'privateCase')}</p><p class="small muted section-space">${t('shareHint')}</p><p class="small muted section-space">${t('sharedText')}</p>${manage?`<div class="section-space">${btn(t(c.shared?'unshareCase':'shareCase'),'sharing-save','users','primary')}</div>`:''}</div>`,true);}
function exportMenu(c) {if(c.status==='processing')return `<span class="pill purple">${icon('clock',14)}${c.progress}% · ${t('processing')}</span>`;return `<details class="export-menu"><summary class="btn">${icon('download',15)}${t('export')}${icon('down',12)}</summary><div class="export-options">${[['docx','wordExport','file'],['html','htmlExport','file'],['xlsx','excelExport','table'],['json','jsonExport','folder']].map(([ext,label,ic])=>`<a href="/api/cases/${c.id}/export/${ext}">${icon(ic,15)}${t(label)}</a>`).join('')}</div></details>`;}
function renderResult() {
  const c=S.current,r=c.result,st=r.stats;
  const tabs=[['findings','risks','alert',st.findings],['structure','units','branch',r.structure.length],['matrix','matrix','table',r.matrix.length],['documents','docs','file',r.documents.length]];
  $('#main').innerHTML=`<div class="result-header"><button class="link-button" data-action="cases" style="margin-bottom:17px;color:#9c9aac">${icon('back',13)}${t('backCases')}</button><div class="between"><div><h1>${esc(c.title)}</h1><div class="result-meta">${statusBadge(c)}<span>${fmtDate(c.created)}</span><span>·</span><span>${esc(c.owner_name)}</span><span>·</span><span>${t(r.method==='hybrid'?'hybrid':'structural')}</span></div></div>${accessButton(c)}${exportMenu(c)}</div></div><div class="result-stats">${[[st.attention,'attention','alert',`${r.findings.filter(f=>f.review!=='pending').length} ${t('reviewed').toLowerCase()}`],[st.structure_changes,'structureChanges','branch',`${r.structure.filter(s=>s.status==='retained').length} ${t('preserved').toLowerCase()}`],[st.matched,'matched','compare',`${st.coverage}% · ${t('coverage')}`],[r.documents.length,'documents','file',t('sourcesVerified')]].map(([value,label,ic,sub])=>`<div class="result-stat card"><div class="stat-top">${t(label)}${icon(ic,16)}</div><div class="stat-value">${value}</div><div class="stat-bottom">${esc(sub)}</div></div>`).join('')}</div><div class="notice">${icon('info',15)}<p>${c.status==='processing'?t('interimResult')+' '+esc(c.stage)+'. ':''}${t('resultNote')}${r.ai.reviewed?` <strong>${t('aiChecked')} ${r.ai.reviewed} ${t('aiOf')} ${r.ai.eligible} ${t('aiCandidates')}.</strong>`:''}${['partial','unavailable'].includes(r.ai.status)?' '+t('aiPartial'):''}</p></div><div class="tabs" role="tablist">${tabs.map(([id,label,ic,n])=>`<button class="tab ${S.tab===id?'active':''}" role="tab" aria-selected="${S.tab===id}" data-action="tab" data-tab="${id}">${icon(ic,15)}${t(label)}<span class="tab-count">${n}</span></button>`).join('')}</div><div id="result-content"></div>${footer()}`;
  renderResultContent();
}
function sourceMap(){ return Object.fromEntries(S.current.result.documents.flatMap(d=>d.clauses.map(c=>[c.id,{...c,document:d}]))); }
function kzDescription(f) {
  const texts={missing:'«Кейін» жиынтығында анық сәйкестік табылмады. Бұл функцияның жойылғанын дәлелдемейді. Жаңа орындаушыны және құжаттардың толықтығын тексеріңіз.',transferred:'Функция мазмұны сақталған немесе жақын, бірақ орындаушылар шеңбері өзгерген. Жауапкершілік шекараларын салыстырыңыз.',modified:'Мазмұны өзгерген жақын тармақ табылды. Әрекетті, нысанды, мерзімдер мен шарттарды тексеріңіз.',modality:'Әрекетті орындаудың міндеттілігі немесе рұқсат шарттары өзгерген. Екі редакциядағы тұжырымды салыстырыңыз.',added:'Жаңа жиынтықта бұрынғы анық сәйкестігі жоқ тармақ пайда болған. Бұл бұрынғы функцияларды нақтылау болуы мүмкін.',editorial:'Тұжырымдар жақын. Редакциялық өзгеріс болуы мүмкін; шағын сөз өзгерісі де мағынаға әсер етеді.',unit_added:'Жаңа құрылымда бөлімше көрсетілген. Бұрынғы тізімнен дәл атау табылмады; қайта атау мүмкіндігін тексеріңіз.',unit_removed:'Бөлімше бұрынғы атаумен табылмады. Қайта атау, біріктіру немесе құрылымнан шығару болуы мүмкін.',overlap:'Жақын функция әртүрлі орындаушыларға бекітілген. Жұмыс нысанын және рөлдер бөлінуін тексеріңіз.',conflict:'Бір орындаушыда жақын нысанды орындау немесе бекіту және тексеру әрекеттері бар. Бұл тексеруді қажет ететін болжам.',safeguard:'Құжат ықтимал мүдделер қақтығысын және/немесе оны болдырмау шараларын сипаттайды. Норманың болуы нақты қақтығысты білдірмейді.'};return texts[f.kind]||f.description;
}
function description(f){return lang==='kz'?kzDescription(f):f.description;}
function filteredFindings() { const q=S.query.toLowerCase(),refs=sourceMap();return S.current.result.findings.filter(f=>(S.filter==='all'||(S.filter==='important'?['high','medium'].includes(f.severity):f.kind===S.filter))&&(S.review==='all'||f.review===S.review)&&(!q||[f.title,f.description,...f.before_ids.concat(f.after_ids).map(id=>refs[id]?.text||'')].join(' ').toLowerCase().includes(q))).sort((a,b)=>({high:0,medium:1,info:2,low:3}[a.severity]-{high:0,medium:1,info:2,low:3}[b.severity])); }
function renderResultContent() {
  if(S.tab==='structure')return renderStructure();if(S.tab==='matrix')return renderMatrix();if(S.tab==='documents')return renderDocuments();
  const r=S.current.result,counts=r.stats.counts;
  $('#result-content').innerHTML=`<div class="filter-bar"><div class="search-box">${icon('search',16)}<input id="finding-search" type="search" placeholder="${t('search')}" value="${esc(S.query)}" aria-label="${t('search')}"></div><select id="review-filter" aria-label="${t('reviewFilter')}">${['all','pending','confirmed','rejected'].map(v=>`<option value="${v}" ${S.review===v?'selected':''}>${t(v)}</option>`).join('')}</select></div><div class="chips">${[['important','important',r.stats.attention],['all','all',r.findings.length],...['missing','transferred','modality','overlap','conflict','added','editorial'].filter(k=>counts[k]).map(k=>[k,'kind_'+k,counts[k]])].map(([key,label,n])=>`<button class="chip ${S.filter===key?'active':''}" data-action="filter" data-filter="${key}">${t(label)}<span>${n}</span></button>`).join('')}</div><div id="findings-results"></div>`;
  renderFindingRows();
}
function pagination(length) {const max=Math.max(1,Math.ceil(length/20));S.page=Math.min(max,S.page);return `<div class="pagination"><span>${t('page')} ${S.page} / ${max} · ${t('findings')}: ${length}</span><div class="flex"><button class="btn sm" data-action="paginate" data-delta="-1" ${S.page<=1?'disabled':''}>${icon('back',13)}${t('prev')}</button><button class="btn sm" data-action="paginate" data-delta="1" ${S.page>=max?'disabled':''}>${t('next')}${icon('arrow',13)}</button></div></div>`;}
function renderFindingRows(){const rows=filteredFindings(),pages=pagination(rows.length),list=rows.slice((S.page-1)*20,S.page*20);$('#findings-results').innerHTML=list.length?`<div class="findings-list">${list.map(f=>`<button class="finding card" data-action="finding" data-id="${f.id}"><div class="finding-type-icon ${f.severity}">${icon(f.kind.startsWith('unit')?'branch':f.kind==='transferred'?'compare':['missing','modality','conflict'].includes(f.kind)?'alert':'file',18)}</div><div class="finding-body"><div class="finding-top">${badge(t('kind_'+f.kind),kindColor(f.kind))}${reviewBadge(f)}${f.ai_review?badge('AI','purple'):''}</div><h3>${esc(f.title)}</h3><div class="finding-description">${esc(description(f))}</div><div class="finding-footer"><span>${icon('link',11)}${f.before_ids.length+f.after_ids.length} ${t('sourceCount')}</span><span><span class="dot"></span>${t(f.severity)}</span></div></div><span class="finding-chevron">${icon('chevron',17)}</span></button>`).join('')}</div>${pages}`:empty(t('noResults'),'',btn(t('resetFilters'),'reset-filters','compare','soft'));}
function renderStructure(){
  const rows=S.current.result.structure;
  const columns=['before','after'].map(side=>{
    const nodes=rows.filter(row=>row[side+'_ids'].length).map(row=>`<button class="unit-node ${row.status}" data-action="source" data-id="${row[side+'_ids'][0]}"><strong>${esc(row.name)}</strong>${badge(t(row.status==='retained'?'preserved':row.status==='added'?'newUnit':'unitMissing'),row.status==='added'?'green':row.status==='missing'?'red':'gray')}</button>`).join('');
    return `<section class="structure-column card"><div class="structure-label">${icon('branch',16)}${t(side)}</div><div class="structure-root">${icon('building',17)}${t('units')}</div><div class="unit-nodes">${nodes}</div></section>`;
  }).join('');
  const body=rows.length?`<div class="structure-grid">${columns}</div><div class="unit-key">${badge(t('retainedUnits'),'gray')}${badge(t('addedUnits'),'green')}${badge(t('removedUnits'),'red')}</div>`:`<div class="card">${empty(t('noUnits'),t('noUnitsText'))}</div>`;
  $('#result-content').innerHTML=`<div class="structure-head"><h2>${t('unitTitle')}</h2><p>${t('unitSubtitle')}</p></div>${body}`;
}
function renderMatrix(){const refs=sourceMap();const rows=S.current.result.matrix.filter(row=>!S.query||[...row.before_ids,...row.after_ids].some(id=>refs[id]?.text.toLowerCase().includes(S.query.toLowerCase())));const pages=pagination(rows.length);const cell=ids=>ids.length?`<span class="source-number">${t('clause')} ${esc(refs[ids[0]].number||'—')}</span><div class="matrix-text">${esc(refs[ids[0]].text)}</div><div class="matrix-actor">${esc(refs[ids[0]].actor)}</div>`:`<span class="muted small">${t('noCorrespondence')}</span>`;$('#result-content').innerHTML=`<div class="filter-bar"><div class="search-box">${icon('search',16)}<input id="matrix-search" type="search" aria-label="${t('search')}" placeholder="${t('search')}" value="${esc(S.query)}"></div><span class="small muted">${rows.length} ${t('fragments')}</span></div><div class="card table-wrap"><div class="table-note">${t('matrixHint')}</div><table class="data-table"><thead><tr><th style="width:19%">${t('status')}</th><th style="width:40%">${t('functionBefore')}</th><th>${t('functionAfter')}</th></tr></thead><tbody>${rows.slice((S.page-1)*20,S.page*20).map(row=>`<tr tabindex="0" data-action="matrix" data-id="${row.id}"><td>${badge(t('kind_'+row.kind),kindColor(row.kind))}</td><td>${cell(row.before_ids)}</td><td>${cell(row.after_ids)}</td></tr>`).join('')}</tbody></table>${!rows.length?empty(t('noResults')):''}</div>${pages}`;}
function renderDocuments(){const docs=S.current.result.documents;$('#result-content').innerHTML=`<div class="doc-grid">${docs.map(d=>`<article class="doc-card card"><div class="doc-header"><div class="doc-symbol">${icon('file',24)}</div><div><h3>${esc(d.name)}</h3><small>${d.format} · ${bytes(d.size)} · ${d.clauses.length} ${t('fragments')}</small></div></div><div class="flex">${badge(t(d.side),d.side==='before'?'purple':'green')}${badge(t(d.warnings.length?'warnings':'noWarnings'),d.warnings.length?'amber':'gray')}</div>${d.warnings.map(w=>`<div class="doc-warning">${icon('info',12)} ${esc(w)}</div>`).join('')}<div class="between"><button class="link-button" data-action="document" data-id="${d.id}">${t('openDocument')}${icon('arrow',13)}</button><a class="icon-button" href="/api/cases/${S.current.id}/documents/${d.id}/download" aria-label="${t('original')}">${icon('download',17)}</a></div></article>`).join('')}</div><p class="small muted section-space">${t('originalLanguage')}</p>`;}
function markDiff(text,other){if(!other)return esc(text);const words=new Set(other.toLowerCase().match(/[\p{L}\p{N}]+/gu)||[]);return text.split(/([\p{L}\p{N}]+)/gu).map(part=>/^[\p{L}\p{N}]+$/u.test(part)&&!words.has(part.toLowerCase())?`<mark>${esc(part)}</mark>`:esc(part)).join('');}
function openModal(markup,center=false){
  if(!S.modal)S.focusBefore=document.activeElement;
  S.modal=true;document.body.style.overflow='hidden';
  $('#modal-root').innerHTML=`<div class="overlay ${center?'modal-center':''}" data-overlay="true"><section class="${center?'modal':'drawer'}" role="dialog" aria-modal="true" aria-labelledby="dialog-title">${markup}</section></div>`;
  const target=$('#modal-root .icon-button')||$('#modal-root input')||$('#modal-root button');target?.focus();
}
function closeModal(){S.modal=null;$('#modal-root').innerHTML='';document.body.style.overflow='';S.focusBefore?.focus?.();}
function dialogHeader(title,back=false){return `<div class="drawer-header"><div class="flex">${back?`<button class="icon-button" data-action="back-finding" aria-label="${t('back')}">${icon('back',18)}</button>`:''}<h2 id="dialog-title">${esc(title)}</h2></div><button class="icon-button" data-action="close" aria-label="${t('close')}">${icon('close',20)}</button></div>`;}
function evidencePanel(ids,side,otherIds){const refs=sourceMap(),c=refs[ids[0]],other=refs[otherIds[0]];return `<section class="evidence-card ${side}"><div class="evidence-header">${icon('file',15)}${t(side)}</div><div class="evidence-content">${c?`<div class="evidence-doc">${esc(c.document.name)}</div><span class="source-number">${t('clause')} ${esc(c.number||'—')}</span><blockquote>${markDiff(c.text,other?.text)}</blockquote><button class="link-button source-link" data-action="source" data-id="${c.id}">${icon('link',12)}${t('fullContext')} · ${esc(c.location)}</button>${ids.length>1?`<details class="context-details"><summary>${t('sourceContext')}</summary>${ids.slice(1).map(id=>`<p><strong>${t('clause')} ${esc(refs[id]?.number)}</strong><br>${esc(refs[id]?.text)}</p>`).join('')}</details>`:''}`:`<div class="source-empty">${icon('search',24)}<p style="margin-top:13px">${t(side==='before'?'noBefore':'noAfter')}</p></div>`}</div></section>`;}
function openFinding(id){
  const f=S.current.result.findings.find(f=>f.id===id);if(!f)return;
  S.activeFinding=id;
  const recommendation=lang==='kz'?'Көрсетілген тармақтарды, орындаушыны және жауапкершілік шекараларын тексеріп, шешімді тіркеңіз.':f.recommendation;
  openModal(`${dialogHeader(t('detail'))}<div class="drawer-body"><div class="flex">${badge(t('kind_'+f.kind),kindColor(f.kind))}${reviewBadge(f)}</div><h2 class="drawer-title">${esc(f.title)}</h2><p class="drawer-description">${esc(description(f))}</p><div class="recommendation"><strong>${icon('spark',13)}${t('recommendation')}</strong><p>${esc(recommendation)}</p></div><h3 class="evidence-heading">${t('sources')}</h3><div class="evidence-grid">${evidencePanel(f.before_ids,'before',f.after_ids)}${evidencePanel(f.after_ids,'after',f.before_ids)}</div>${f.candidate_id&&!f.after_ids.length?`<div class="section-space"><button class="link-button" data-action="source" data-id="${esc(f.candidate_id)}">${icon('search',13)}${t('closest')}</button></div>`:''}${f.ai_review?`<div class="ai-opinion"><h3>${icon('spark',14)} ${t('aiOpinion')} · ${t({equivalent:'aiEquivalent',changed:'aiChanged',unmatched:'aiUnmatched',uncertain:'aiUncertain'}[f.ai_review.relation])}</h3><p>${esc(f.ai_review.reason)}</p></div>`:''}<section class="review-panel card"><div class="between"><h3>${t('analystDecision')}</h3>${badge(t(f.review),f.review==='confirmed'?'green':f.review==='rejected'?'gray':'purple')}</div>${writable()&&S.current.status==='complete'?`<label class="field"><span>${t('comment')}</span><textarea id="review-comment" maxlength="3000" placeholder="${t('commentPlaceholder')}">${esc(f.comment)}</textarea></label><div class="review-actions">${btn(t('confirm'),'review','check','success',`data-id="${f.id}" data-status="confirmed"`)}${btn(t('reject'),'review','close','danger',`data-id="${f.id}" data-status="rejected"`)}${btn(t('saveComment'),'review','file','',`data-id="${f.id}" data-status="${f.review}"`)}${f.review!=='pending'?`<button class="link-button" data-action="review" data-id="${f.id}" data-status="pending">${t('resetReview')}</button>`:''}</div>`:`<p class="small muted">${t(S.current.status==='processing'?'waitReview':'readOnly')}</p>${f.comment?`<p style="margin-top:12px">${esc(f.comment)}</p>`:''}`}${f.reviewer?`<div class="review-meta">${t('reviewer')}: ${esc(f.reviewer)} · ${fmtTime(f.reviewed_at)}</div>`:''}</section><p class="small muted section-space">${t('similarity')}: ${Math.round(f.score*100)}%. ${t('similarityHint')}</p></div>`);
}
function openMatrix(id){const row=S.current.result.matrix.find(r=>r.id===id);if(!row)return;if(row.finding_id)return openFinding(row.finding_id);S.activeFinding=null;openModal(`${dialogHeader(t('matrix'))}<div class="drawer-body">${badge(t('kind_'+row.kind),kindColor(row.kind))}<h3 class="evidence-heading">${t('sources')}</h3><div class="evidence-grid">${evidencePanel(row.before_ids,'before',row.after_ids)}${evidencePanel(row.after_ids,'after',row.before_ids)}</div></div>`);}
function openDocument(id,clauseId=''){
  const doc=S.current.result.documents.find(d=>d.id===id);if(!doc)return;
  S.readerDoc=id;
  openModal(`${dialogHeader(t('sourceViewer'),!!S.activeFinding)}<div class="drawer-body"><div class="source-toolbar"><div class="source-title"><h2>${esc(doc.name)}</h2><p>${doc.format} · ${doc.clauses.length} ${t('fragments')} · ${t(doc.side)}</p></div><a class="btn sm" href="/api/cases/${S.current.id}/documents/${doc.id}/download">${icon('download',15)}${t('original')}</a></div><div class="filter-bar"><div class="search-box">${icon('search',16)}<input id="source-search" type="search" placeholder="${t('search')}" aria-label="${t('search')}"></div></div><div class="document-text" id="document-text">${doc.clauses.map(c=>`<div class="source-clause ${c.kind} ${c.id===clauseId?'highlight':''}" id="src-${c.id}" data-source-text="${esc(c.text.toLowerCase())}"><small>${esc(c.location)}${c.number?' · '+t('clause')+' '+esc(c.number):''}</small><p>${esc(c.text)}</p></div>`).join('')}</div>${doc.source_url?`<p class="section-space"><a class="link-button" href="${esc(doc.source_url)}" target="_blank" rel="noopener noreferrer">${t('sourceLink')}${icon('arrow',13)}</a></p>`:''}</div>`);
  if(clauseId)requestAnimationFrame(()=>$('#src-'+clauseId)?.scrollIntoView({block:'center'}));
}
function openSource(cid){const c=sourceMap()[cid];if(c)openDocument(c.doc_id,cid);}
function renderMethod(){ $('#main').innerHTML=`<div class="page-heading"><div><h1>${t('methodTitle')}</h1><p>${t('methodText')}</p></div></div><div class="method-grid">${[1,2,3,4].map(i=>`<article class="method-card card"><div class="method-number">0${i}</div><h3>${t('method'+i)}</h3><p>${t('method'+i+'Text')}</p></article>`).join('')}</div><div class="limitations card"><h2>${t('limitations')}</h2><ul>${[1,2,3,4].map(i=>`<li>${t('limit'+i)}</li>`).join('')}</ul></div>${footer()}`;}
function renderSettings(){const ai=S.config.ai;$('#main').innerHTML=`<div class="page-heading"><div><h1>${t('settingsTitle')}</h1></div></div><div class="settings-grid"><section class="settings-card card"><div class="between"><h2>${t('model')}</h2>${badge(t(ai.available?'connected':'disconnected'),ai.available?'green':'gray')}</div><div class="model-info"><div class="stat-icon">${icon('spark',22)}</div><div><strong>${esc(ai.model)}</strong><small>${esc(ai.provider)} · ${t(ai.local?'local':'external')}</small></div></div><p>${t('configHelp')}</p><pre>AI_PROVIDER=ollama\nAI_BASE_URL=http://127.0.0.1:11434\nAI_MODEL=qwen2.5:7b\nAI_MAX_PAIRS=20</pre><div class="notice">${icon('info',15)}<p>${t(ai.local?'aiLocal':'aiRemote')}</p></div></section><div class="stack"><section class="settings-card card"><h2>${icon('users',18)} ${t('sharedTitle')}</h2><p>${t('sharedText')}</p></section><section class="settings-card card"><h2>${icon('shield',18)} ${t('securityTitle')}</h2><p>${t('securityText')}</p><div class="section-space">${btn(t('changePassword'),'password','lock','')}</div></section></div></div><div class="card card-pad section-space"><h3>${t('limitations')}</h3><p class="small section-space">${t('uploadLimits')}</p><p class="small" style="margin-top:10px">PDF: ≤ ${S.config.limits.pdf_pages} ${lang==='kz'?'бет / файл':'страниц / файл'} · ≤ ${S.config.limits.function_fragments} ${t('fragments')} / ${t('cases').toLowerCase()}</p></div>${footer()}`;}
async function renderTeam(){if(S.user.role!=='admin')return go('home');const users=await api('/api/users');if(!location.hash.includes('/team'))return;$('#main').innerHTML=`<div class="page-heading"><div><h1>${t('teamTitle')}</h1><p>${t('teamSubtitle')}</p></div>${btn(t('addUser'),'add-user','plus')}</div><div class="card table-wrap"><table class="data-table"><thead><tr><th>${t('name')}</th><th>${t('username')}</th><th>${t('role')}</th><th>${t('status')}</th><th></th></tr></thead><tbody>${users.map(u=>`<tr><td><div class="flex"><div class="avatar">${esc(u.name.slice(0,2).toUpperCase())}</div><strong>${esc(u.name)}</strong>${u.id===S.user.id?badge(t('you'),'gray'):''}</div></td><td>${esc(u.username)}</td><td>${u.id===S.user.id?t(u.role):`<select id="role-${u.id}" aria-label="${t('role')}: ${esc(u.name)}">${['admin','analyst','viewer'].map(r=>`<option value="${r}" ${r===u.role?'selected':''}>${t(r)}</option>`).join('')}</select>`}</td><td>${u.id===S.user.id?badge(t('active'),'green'):`<select id="active-${u.id}" aria-label="${t('status')}: ${esc(u.name)}"><option value="1" ${u.active?'selected':''}>${t('active')}</option><option value="0" ${!u.active?'selected':''}>${t('disabled')}</option></select>`}</td><td>${u.id!==S.user.id?btn(t('save'),'user-access','check','sm',`data-id="${u.id}"`):''}</td></tr>`).join('')}</tbody></table></div><div class="notice section-space">${icon('users',15)}<p>${t('sharedText')}</p></div>${footer()}`;}
async function renderAudit(){if(S.user.role!=='admin')return go('home');const rows=await api('/api/audit');if(!location.hash.includes('/audit'))return;const names=lang==='kz'?{setup:'Әкімші құрылды',login:'Жүйеге кіру',user_created:'Пайдаланушы қосылды',user_access_changed:'Қол жеткізу өзгерді',password_changed:'Құпиясөз өзгерді',review:'Қорытынды тексерілді',analysis_created:'Талдау басталды',demo_created:'Мысал талдауы',analysis_completed:'Талдау аяқталды',document_downloaded:'Түпнұсқа жүктелді',report_exported:'Есеп жүктелді'}:{setup:'Создан администратор',login:'Вход в систему',user_created:'Добавлен пользователь',user_access_changed:'Изменён доступ',password_changed:'Изменён пароль',review:'Проверка вывода',analysis_created:'Запущен анализ',demo_created:'Запущен пример',analysis_completed:'Анализ завершён',document_downloaded:'Скачан оригинал',report_exported:'Выгружен отчёт'};$('#main').innerHTML=`<div class="page-heading"><div><h1>${t('auditTitle')}</h1><p>${t('auditSubtitle')}</p></div></div><div class="card table-wrap"><table class="data-table"><thead><tr><th>${t('date')}</th><th>${t('name')}</th><th>${t('action')}</th><th>${t('target')}</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${fmtTime(r.time)}</td><td>${esc(r.name||'—')}</td><td>${esc(names[r.action]||r.action)}</td><td class="muted">${esc(r.detail||r.target?.slice(0,12)||'—')}</td></tr>`).join('')}</tbody></table></div>${footer()}`;}
async function renderGlobalDocs(){const cases=S.cases.filter(c=>c.status==='complete');$('#main').innerHTML=`<div class="page-heading"><div><h1>${t('docs')}</h1><p>${t('originalLanguage')}</p></div></div>${cases.length?`<div class="card">${cases.map(c=>`<div class="case-row"><div class="case-icon">${icon('folder',20)}</div><div class="case-info"><strong>${esc(c.title)}</strong><small>${c.stats?.source_count||0} ${t('documents').toLowerCase()} · ${fmtDate(c.created)}</small></div><button class="link-button" data-action="case-docs" data-id="${c.id}">${t('open')}${icon('arrow',14)}</button></div>`).join('')}</div>`:`<div class="card">${empty(t('emptyDocs'),'',writable()?btn(t('start'),'new'):'')}</div>`}${footer()}`;}
async function route(){
  if(!S.user)return renderAuth();
  clearTimeout(S.timer);closeModal();S.activeFinding=null;
  const token=++S.routeToken,parts=(location.hash||'#/home').replace(/^#\//,'').split('/'),view=parts[0]||'home';
  document.documentElement.lang=lang==='kz'?'kk':'ru';document.title=`AI-NAM · ${t(view==='case'?'cases':view==='new'?'newAnalysis':view)}`;
  shell(view);$('#main').innerHTML=loading();window.scrollTo(0,0);
  try{
    if(view==='home'||view==='cases'||view==='docs'){S.cases=await api('/api/cases');if(token!==S.routeToken)return;shell(view);if(view==='home')renderHome();if(view==='cases')renderCases();if(view==='docs')renderGlobalDocs();}
    else if(view==='new')renderNew();
    else if(view==='case'){
      const c=await api('/api/cases/'+encodeURIComponent(parts[1]));if(token!==S.routeToken)return;S.current=c;
      if(c.status==='processing'){renderProcessing(c);pollCase(c.id,token);}
      else if(c.status==='failed')$('#main').innerHTML=`<div class="error-box card"><div class="empty-icon">${icon('alert',30)}</div><h2>${t('failed')}</h2><p>${esc(c.error)}</p>${btn(t('retry'),'new','compare')}</div>`;
      else renderResult();
    }
    else if(view==='method')renderMethod();else if(view==='settings')renderSettings();else if(view==='team')await renderTeam();else if(view==='audit')await renderAudit();else go('home');
  }catch(e){if(token!==S.routeToken||!S.user)return;$('#main').innerHTML=`<div class="error-box card"><h2>${t('error')}</h2><p>${esc(e.message)}</p>${btn(t('backCases'),'cases','back')}</div>`;}
}
function pollCase(id,token){S.timer=setTimeout(async()=>{try{const c=await api('/api/cases/'+id);if(token!==S.routeToken)return;S.current=c;if(c.status==='processing'){renderProcessing(c);pollCase(id,token);}else{S.cases=await api('/api/cases');if(token===S.routeToken){if(c.status==='complete'){renderResult();if(S.modal&&S.activeFinding&&!$('#document-text'))openFinding(S.activeFinding);}else route();}}}catch(e){if(token!==S.routeToken)return;toast(e.message,true);pollCase(id,token);}},1800);}
function demoModal(){const ai=S.config.ai;openModal(`${dialogHeader(t('demoTitle'))}<div class="modal-body"><p class="small muted">${t('demoText')}</p><div class="notice section-space">${icon('file',16)}${t('demoFiles')} · ${t('demoVersions')}</div><label class="ai-choice"><input type="checkbox" id="demo-ai" ${ai.available&&ai.local?'checked':''} ${!ai.available?'disabled':''}><div><strong>${t('aiMode')}</strong><p>${t(!ai.available?'aiUnavailable':ai.local?'aiLocal':'aiRemote')}</p></div></label><div class="section-space">${btn(t('analyze'),'demo-run','compare','primary full')}</div></div>`,true);}
async function startDemo(button){button.disabled=true;try{const data=await api('/api/demo',{method:'POST',body:JSON.stringify({use_ai:!!$('#demo-ai')?.checked})});S.tab='findings';S.filter='important';S.query='';S.page=1;go('case/'+data.id);}catch(e){toast(e.message,true);button.disabled=false;}}
function addUserModal(){openModal(`${dialogHeader(t('addUser'))}<form id="user-form" class="modal-body"><div id="user-error" role="alert"></div><label class="field"><span>${t('name')}</span><input name="name" minlength="2" maxlength="100" required autocomplete="off"></label><label class="field"><span>${t('username')}</span><input name="username" pattern="[a-zA-Z0-9_.\-]+" minlength="3" maxlength="60" required autocomplete="off"></label><label class="field"><span>${t('password')}</span><input type="password" name="password" minlength="10" maxlength="200" required autocomplete="new-password"><small>${t('passwordHint')}</small></label><label class="field"><span>${t('role')}</span><select name="role">${['analyst','viewer','admin'].map(r=>`<option value="${r}">${t(r)}</option>`).join('')}</select></label><div class="flex"><button class="btn primary" type="submit">${t('addUser')}</button><button class="btn ghost" type="button" data-action="close">${t('cancel')}</button></div></form>`,true);}
function passwordModal(){openModal(`${dialogHeader(t('changePassword'))}<form id="password-form" class="modal-body"><div id="password-error" role="alert"></div><label class="field"><span>${t('currentPassword')}</span><input type="password" name="current_password" autocomplete="current-password" maxlength="200" required></label><label class="field"><span>${t('newPassword')}</span><input type="password" name="new_password" autocomplete="new-password" minlength="10" maxlength="200" required><small>${t('passwordHint')}</small></label><button class="btn primary" type="submit">${t('save')}</button></form>`,true);}
document.addEventListener('click',async event=>{
  if(event.target.dataset.overlay){closeModal();return;}
  const button=event.target.closest('[data-action]');if(!button||button.disabled)return;
  const a=button.dataset.action;
  try{
    if(a==='language'){lang=button.dataset.lang;localStorage.setItem('ai-nam-lang',lang);if(S.user)route();else renderAuth();}
    else if(a==='new')go('new');else if(a==='cases')go('cases');else if(a==='reload')boot();
    else if(a==='menu')$('#sidebar').classList.toggle('open');
    else if(a==='logout'){await api('/api/auth/logout',{method:'POST'});S.user=null;S.current=null;S.files={before:[],after:[]};renderAuth();}
    else if(a==='demo')demoModal();else if(a==='demo-run')await startDemo(button);
    else if(a==='case'){S.tab='findings';S.query='';S.filter='important';S.review='all';S.page=1;go('case/'+button.dataset.id);}
    else if(a==='case-docs'){S.tab='documents';go('case/'+button.dataset.id);}
    else if(a==='browse')$('#files-'+button.dataset.side).click();
    else if(a==='remove-file'){S.files[button.dataset.side].splice(+button.dataset.index,1);renderFiles();}
    else if(a==='tab'){S.tab=button.dataset.tab;S.query='';S.page=1;renderResult();}
    else if(a==='filter'){S.filter=button.dataset.filter;S.page=1;renderResultContent();}
    else if(a==='reset-filters'){S.filter='all';S.query='';S.review='all';S.page=1;renderResultContent();}
    else if(a==='paginate'){S.page+=+button.dataset.delta;if(S.tab==='matrix')renderMatrix();else renderFindingRows();$('#result-content').scrollIntoView({block:'start',behavior:'smooth'});}
    else if(a==='finding')openFinding(button.dataset.id);
    else if(a==='matrix')openMatrix(button.dataset.id);
    else if(a==='source')openSource(button.dataset.id);
    else if(a==='document'){S.activeFinding=null;openDocument(button.dataset.id);}
    else if(a==='back-finding')openFinding(S.activeFinding);
    else if(a==='close')closeModal();
    else if(a==='review'){
      button.disabled=true;const updated=await api(`/api/cases/${S.current.id}/findings/${button.dataset.id}`,{method:'PATCH',body:JSON.stringify({status:button.dataset.status,comment:$('#review-comment').value})});const index=S.current.result.findings.findIndex(f=>f.id===updated.id);S.current.result.findings[index]=updated;renderResult();openFinding(updated.id);toast(t('saved'));
    }
    else if(a==='sharing')sharingModal();
    else if(a==='sharing-save'){button.disabled=true;const updated=await api(`/api/cases/${S.current.id}/sharing`,{method:'PATCH',body:JSON.stringify({shared:!S.current.shared})});S.current.shared=updated.shared;closeModal();renderResult();toast(t('accessSaved'));}
    else if(a==='add-user')addUserModal();else if(a==='password')passwordModal();
    else if(a==='user-access'){button.disabled=true;await api('/api/users/'+button.dataset.id,{method:'PATCH',body:JSON.stringify({role:$('#role-'+button.dataset.id).value,active:$('#active-'+button.dataset.id).value==='1'})});toast(t('saved'));await renderTeam();}
  }catch(e){toast(e.message,true);button.disabled=false;}
});
document.addEventListener('submit',async event=>{
  const form=event.target;if(!['auth-form','upload-form','user-form','password-form'].includes(form.id))return;
  event.preventDefault();const submit=$('button[type=submit]',form),data=Object.fromEntries(new FormData(form));let errorId='';
  try{
    if(form.id==='auth-form'){
      errorId='auth-error';if(S.setup&&data.password!==data.confirmation)throw new Error(t('passwordMismatch'));submit.disabled=true;
      const auth=await api(S.setup?'/api/auth/setup':'/api/auth/login',{method:'POST',body:JSON.stringify(data)});S.user=auth.user;S.setup=false;await loadWorkspace();if(!location.hash)location.hash='#/home';else route();
    }else if(form.id==='upload-form'){
      errorId='upload-error';if(!S.files.before.length||!S.files.after.length)throw new Error(t('missingFiles'));
      submit.disabled=true;S.title=$('#case-title').value;const body=new FormData();body.append('title',S.title);body.append('use_ai',$('#use-ai').checked?'true':'false');for(const side of ['before','after'])for(const file of S.files[side])body.append(side,file);
      const created=await api('/api/cases',{method:'POST',body});S.files={before:[],after:[]};S.title='';S.tab='findings';S.filter='important';S.query='';S.page=1;go('case/'+created.id);
    }else if(form.id==='user-form'){
      errorId='user-error';submit.disabled=true;await api('/api/users',{method:'POST',body:JSON.stringify(data)});closeModal();toast(t('userCreated'));await renderTeam();
    }else if(form.id==='password-form'){
      errorId='password-error';submit.disabled=true;await api('/api/auth/password',{method:'POST',body:JSON.stringify(data)});closeModal();toast(t('passwordChanged'));
    }
  }catch(e){const target=$('#'+errorId);if(target)target.innerHTML=`<div class="form-error">${esc(e.message)}</div>`;else toast(e.message,true);if(submit)submit.disabled=false;}
});
document.addEventListener('change',event=>{
  const el=event.target;
  if(el.dataset.files){addFiles(el.dataset.files,[...el.files]);el.value='';}
  else if(el.id==='review-filter'){S.review=el.value;S.page=1;renderFindingRows();}
  else if(el.id==='use-ai')S.useAI=el.checked;
});
let searchTimer;
document.addEventListener('input',event=>{
  const el=event.target;
  if(el.id==='case-title')S.title=el.value;
  else if(el.id==='finding-search'){S.query=el.value;S.page=1;clearTimeout(searchTimer);searchTimer=setTimeout(renderFindingRows,140);}
  else if(el.id==='matrix-search'){S.query=el.value;S.page=1;clearTimeout(searchTimer);searchTimer=setTimeout(()=>{const pos=el.selectionStart;renderMatrix();const field=$('#matrix-search');field.focus();if(field.type!=='search')field.setSelectionRange(pos,pos);},250);}
  else if(el.id==='source-search'){const q=el.value.toLowerCase();$$('.source-clause').forEach(c=>c.hidden=q&&!c.dataset.sourceText.includes(q));}
});
document.addEventListener('dragover',event=>{const drop=event.target.closest('[data-drop]');if(drop){event.preventDefault();drop.classList.add('drag');}});
document.addEventListener('dragleave',event=>{const drop=event.target.closest('[data-drop]');if(drop&&!drop.contains(event.relatedTarget))drop.classList.remove('drag');});
document.addEventListener('drop',event=>{const drop=event.target.closest('[data-drop]');if(drop){event.preventDefault();drop.classList.remove('drag');addFiles(drop.dataset.drop,[...event.dataTransfer.files]);}});
document.addEventListener('keydown',event=>{
  if(event.key==='Escape'){closeModal();$('#sidebar')?.classList.remove('open');}
  if(event.key==='Enter'&&event.target.matches('tr[data-action]'))event.target.click();
  if(event.key==='Tab'&&S.modal){const items=$$('button:not([disabled]),a[href],input,select,textarea,summary',$('#modal-root')).filter(e=>e.getClientRects().length);const first=items[0],last=items[items.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}
});
window.addEventListener('hashchange',route);
boot();
